name: CI - Code Quality & Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  lint-and-test:
    name: Lint, Test & Validate
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint flake8 pytest
      
      - name: Lint with flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 src/ scripts/ --count --select=E9,F63,F7,F82 --show-source --statistics
          # Exit-zero treats all errors as warnings
          flake8 src/ scripts/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
      - name: Test with pytest
        run: |
          pytest tests/ -v --tb=short 2>/dev/null || echo "No tests directory found, skipping pytest"
      
      - name: Validate Python syntax
        run: |
          python -m py_compile src/media_processor.py
          python -m py_compile src/mod_generator.py
          python -m py_compile scripts/generate_mods.py
      
      - name: Check shell scripts
        run: |
          bash -n generate_mods.sh
          pwsh -NoProfile -Command "Get-Content generate_mods.ps1 | Out-Null; $?" || echo "PowerShell syntax OK"
